parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'

ignorePatterns:
  - 'build'

plugins:
  - '@typescript-eslint'
  - 'prettier'
  - 'jest'

extends:
  - 'eslint:recommended'
  - 'standard-with-typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:prettier/recommended'
  - 'plugin:jest/all'

rules:
  '@typescript-eslint/consistent-type-definitions': ['error', 'type']
  '@typescript-eslint/promise-function-async': 'off'
  'jest/no-hooks': 'off'
  'jest/prefer-lowercase-title': 'off'
