name: Integration

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
  schedule:
    - cron: '0 20 * * *'

jobs:
  test:
    name: test integration with rozetka api
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm install
      - run: npm run test:integration
